apiVersion: v1
kind: Service
metadata:
  name: complex-service
  labels:
    app: complex-app
  annotations:
    description: "This is a complex service with multiple ports and session affinity enabled"
spec:
  type: NodePort    # Exposes the service on a static port on every node's IP
  selector:
    app: complex-app
  sessionAffinity: ClientIP   # Ensures that traffic from the same client is sent to the same pod
  ports:
    - name: http
      protocol: TCP
      port: 80         # Internal port exposed by the service
      targetPort: 8080 # Port on the pods that serve HTTP traffic
      nodePort: 30080  # Static port on nodes for external access to HTTP
    - name: https
      protocol: TCP
      port: 443         # Internal port exposed for HTTPS traffic
      targetPort: 8443  # Port on the pods that serve HTTPS traffic
      nodePort: 30443   # Static port on nodes for external access to HTTPS
