apiVersion: v1
kind: Secret
metadata:
  name: advanced-secret
  namespace: default
  annotations:
    description: "TLS certificate for production application"
  labels:
    tier: backend
    environment: production
type: kubernetes.io/tls
data:
  # Replace the following dummy Base64 strings with your actual certificate and key.
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCkR1bW15Q2VydGlmaWNhdGVEYXRh...
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQo=
