apiVersion: v1
kind: Secret
metadata:
  name: complex-secret
  namespace: default
  labels:
    app: myapp
type: Opaque
stringData:
  # Plain text values that Kubernetes will automatically encode in Base64.
  username: complexUser
  password: ComplexPassword123!
  apiKey: abcdef123456
  config.json: |
    {
      "endpoint": "https://api.example.com",
      "timeout": 30,
      "retry": 3
    }
