apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod                             # Unique name for the Pod
  labels:
    app: advanced-demo                           # Label for grouping and selection
    environment: production                      # Label to indicate the environment
spec:
  # Init Containers: run before regular containers start
  initContainers:
  - name: init-myservice
    image: busybox:1.31                          # Lightweight image to perform init tasks
    command: ["sh", "-c", "echo Initializing... && sleep 5"]
    # Resources for the init container
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
  
  # Define volumes used by the Pod
  volumes:
  - name: config-volume                           # Volume for configuration files from a ConfigMap
    configMap:
      name: my-config                             # Reference to an existing ConfigMap
  - name: secret-volume                           # Volume for sensitive data from a Secret
    secret:
      secretName: my-secret                       # Reference to an existing Secret
  - name: persistent-storage                      # Volume for persistent data via PVC
    persistentVolumeClaim:
      claimName: my-pvc                           # Reference to a PersistentVolumeClaim
  
  # Main containers
  containers:
  - name: main-container
    image: myapp:2.0                              # Main application image
    ports:
    - containerPort: 8080                         # Expose port for application traffic
    env:
    - name: ENVIRONMENT
      value: "production"                         # Static environment variable
    - name: CONFIG_PATH
      value: "/etc/config/app.conf"               # Path to a configuration file
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret                         # Get secret key from the Secret
          key: secret-key
    volumeMounts:
    - name: config-volume                         # Mount ConfigMap volume
      mountPath: /etc/config                      # Directory in container for config files
    - name: secret-volume                         # Mount Secret volume
      mountPath: /etc/secret                      # Directory in container for secrets
    - name: persistent-storage                    # Mount PVC for persistent data
      mountPath: /data                            # Directory in container for persistent storage
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    livenessProbe:                                # Probe to check if the container is alive
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 15
    readinessProbe:                               # Probe to check if the container is ready to serve traffic
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
  
  - name: sidecar-logger
    image: fluentd:latest                         # Sidecar container for logging
    env:
    - name: FLUENTD_CONF
      value: "fluent.conf"                        # Fluentd configuration file
    volumeMounts:
    - name: persistent-storage                    # Share persistent storage to access logs
      mountPath: /var/log/myapp                   # Directory where logs are written
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

  # Restart policy for the Pod (Always, OnFailure, Never)
  restartPolicy: Always
